name: radiantabundance
favicon: null
layout_spectrum: 0.5397349344566464
typography_spectrum: 0.6938319916371256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27106946776621044
  lightness: 0.22036962490528822
  saturation: 0.8496597080957144
  rhythmicContrast: 0.8100147203076631
purpose: []
